version: '3.8'

services:
  urlpostgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./migrations:/migrations
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: urlpostgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: postgres
      DB_SSLMODE: disable
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: "0"
    depends_on:
      - urlpostgres
      - redis
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
  redis_data: