version: '3.8'

services:
  urlpostgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./migrations:/migrations
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hydra-network

  ory-hydra:
    image: oryd/hydra:v1.10.6
    command: serve all --dangerous-force-http
    environment:
      SECRETS_SYSTEM: eb30e7ed967d775a42c65a915f255321
      DSN: postgres://postgres:mysecretpassword@urlpostgres:5432/postgres?sslmode=disable
      URLS_SELF_ISSUER: http://localhost:4444/
      URLS_CONSENT: http://localhost:3000/consent
      URLS_LOGIN: http://localhost:3000/login
      URLS_LOGOUT: http://localhost:3000/logout
      OAUTH2_EXPOSE_INTERNAL_ERRORS: "true"
    ports:
      - "4444:4444"
      - "4445:4445"
    depends_on:
      - urlpostgres
    networks:
      - hydra-network

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - hydra-network

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: urlpostgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: postgres
      DB_SSLMODE: disable
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: "0"
    depends_on:
      - urlpostgres
      - redis
    networks:
      - hydra-network


networks:
  hydra-network:
    name: hydra-network
    driver: bridge

volumes:
  postgres_data: 
  redis_data:   
